package:
  name: xerces-c
  version: "3.1.3"

source:
  fn: xerces-c-3.1.3.tar.gz [not win]
  fn: xerces-c-3.1.3.zip [win]
  url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.1.3.tar.gz [not win]
  url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.1.3.zip [win]

build:
  number: 1

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache 2.0
